#!/bin/bash
#
# This script runs the image generated by the docker build script
# using docker run command, where:
#   --rm  automatically removes the container and on exit
#   -i  keeps the standard input open
#   -t  provides a terminal as a interactive shell within container
#   --volumes  are file systems mounted on docker container to preserve
# data generated during the yocto build and these are stored on the host.
# Left side being an absolute path on the host machine, right side being
# an absolute path inside the container.
#

# source the common variables
. ./env.sh

if [[ $PWD != $HOME* && $(whoami) != "root" ]]; then
    echo "Error: Current directory is outside $HOME"
    exit 1
fi

if [ -t 0 ]; then
    INTERACTIVE_RUN_PARAMS="-it"
fi

# run the docker image
$CONTAINER_ENGINE run ${INTERACTIVE_RUN_PARAMS} --rm \
  ${CONTAINER_RUN_PARAMS} \
  --volume ${HOME}:${HOME} \
  --device /dev/net/tun \
  --cap-add=NET_ADMIN \
  -e "MACHINE=${MACHINE}" \
  -e "DOWNLOADS_DIR=${DOWNLOADS_DIR}" \
  -e "SSTATE_DIR=${SSTATE_DIR}" \
    "${IMAGE_TAG}" \
    "$@"
