#!/bin/bash
#
# This script runs the image generated by the docker build script
# using docker run command, where:
#   --rm  automatically removes the container and on exit
#   -i  keeps the standard input open
#   -t  provides a terminal as a interactive shell within container
#   --volumes  are file systems mounted on docker container to preserve
# data generated during the yocto build and these are stored on the host.
# Left side being an absolute path on the host machine, right side being
# an absolute path inside the container.
#

# source the common variables
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. $ROOT_DIR/env.sh

if [[ $PWD != $HOME* && $(whoami) != "root" ]]; then
    echo "Error: Current directory is outside $HOME"
    exit 1
fi

if [ "$#" -gt 0 ]; then
  COMMAND="$*"
else
  COMMAND="exec bash"
fi

# run the docker image
BUILDS_DIR="${PWD}/builds"
$CONTAINER_ENGINE run -it --rm \
  ${CONTAINER_RUN_PARAMS} \
  --device /dev/net/tun \
  --volume "${HOME}":"${HOME}" \
  --volume meta-swift-examples:"${BUILDS_DIR}" \
  --cap-add=NET_ADMIN \
  "${IMAGE_TAG}" \
  /bin/bash -c "sudo chown $(id -u):$(id -g) ${BUILDS_DIR} && $COMMAND"
