name: Build & Run

on:
  workflow_dispatch:

jobs:
  runqemu:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false
          submodules: recursive
      - name: Build Container
        run: ./build-container.sh
      - name: Build Yocto
        run: ./run-container.sh ./build.sh
      - name: Run Swift Hello World (qemu)
        run: ./run-container.sh ./execute.exp
