name: Build & Run

on:
  workflow_dispatch:
    inputs:
      clean_build:
        description: 'Run Clean Build'
        type: boolean
        default: false

jobs:
  runqemu:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false
          submodules: recursive
      - name: Build Container
        run: ./build-container.sh
      - name: Clean Build Directory
        if: ${{ github.event.inputs.clean_build == 'true' }}
        run: |
          rm -rf poky/build*
          rm -rf sstate-cache
      - name: Build Yocto
        run: ./run-container.sh ./build.sh
      - name: Run Swift Hello World (qemu)
        run: ./run-container.sh ./execute.exp
